### ISSUE TITLE
Cannot import .obj file

### ISSUE THREAD

**Issue by vanneop** [rodrigorc/papercraft#1]
Installed papercraft on Windows 10, 64-bit. When I try to import an obj file, I get the following error message:

Error reading Wavefront file C:\Users\vn\build\papercraft\body.obj

Caused by:
    0: Error reading matlib file C:\Users\vn\build\papercraft\
    1: The system cannot find the path specified. (os error 3)

Is this error message caused by something being wrong in my installation, or it has to do with papercraft itself?

Thanks

**Comment by rodrigorc** [comment]
The OBJ format contains the path of the matlib file that defines the material. Some programs like to add here an absolute path, so if you save your file as `c:\users\vanneop\body.obj`, the mtl file will be `c:\users\vanneop\body.mtl`. But then if you move the file somewhere else the mtl file reference may be broken.

As a workaround, I try to read the mtl with that absolute path, and then, if not found, I remove the directory part and search it in the same directory as the obj file.

Can you try opening the `body.obj` file with notepad, looking for the `mtllib` line and checking whether the referenced file exists? If it does not, try looking for it wherever you found the original OBJ and move it to the same directory.

Alternatively you can delete the line with `mtllib` and any other `usemtl` from the file.

**Comment by vanneop** [comment]
Thank you very much for your help. After I corrected the .mtl file path in
the .obj file everything worked fine. Thank you for providing such a useful
tool.
