### ISSUE TITLE
texture does not appear 

### ISSUE THREAD

**Issue by Bwangp** [rodrigorc/papercraft#10]
I am uses kubuntu linux 24.04 

i import with obj file and texture does not appear 

![Screenshot_20240927_174524](https://github.com/user-attachments/assets/5efd29ad-ee83-40aa-a022-905b6345d890)

**Comment by rodrigorc** [comment]
Hi, @Bwangp.

It is easy to export an OBJ and not set the material/texture properly. Usually when that happens an error is shown when loading the model. But sometimes there is no error or texture to show.

Could you share the OBJ/MTL files here?

**Comment by Bwangp** [comment]
i didn't know whats wrong with it 

Export with blender 3.6.0
[primogem.zip](https://github.com/user-attachments/files/17166033/primogem.zip)

**Comment by rodrigorc** [comment]
Ok, I can see that the model has a material and texture coordinates but there is no actual texture.

The texture image is defined inside the MTL file, as a `map_Kd` line, but your file doesn't have it.

You can add it manually, with any text editor, and reference to a PNG file on the same directory. Let me add one here in case it helps, with a random PNG image:
```
newmtl Material.001
map_Kd primogem.png
```
[primogem_mtl.zip](https://github.com/user-attachments/files/17166430/primogem_mtl.zip)

Naturally, the proper way is for Blender to do this automatically. Blender 3.6 is a bit old, and its OBJ exporter was clunky, but it should work.

Maybe your Blender material is not properly textured? If you share the `.blend` file here I'll take a look and try to export it using my Blender.

**Comment by Bwangp** [comment]
[primogem.zip](https://github.com/user-attachments/files/17171673/primogem.zip)

**Comment by Bwangp** [comment]
It worked! 
![Screenshot_20240928_073947](https://github.com/user-attachments/assets/dbe1c42e-d643-4c39-b95a-ee4e55f35f65)
[primogem.pdf](https://github.com/user-attachments/files/17171695/primogem.pdf)

**Comment by rodrigorc** [comment]
Great! I'm closing the issue. If you have further problems, just reopen, attach the blend file and we'll check it out.
