### ISSUE TITLE
Bug in rendering 3d model and flat pieces

### ISSUE THREAD

**Issue by Pokefan1067** [rodrigorc/papercraft#12]
When I use the software, both the 3d model and the paper both don’t show up. I use the x64 edition of papercraft on windows 11. When I use the export to pdf option however, it outputs the pdf file just fine. The file works too. It also doesn’t show the 3d model of the example models too. Any ideas what’s wrong?

**Comment by Pokefan1067** [comment]
I tried using the integrated graphics on my PC and the problem was fixed. If you want to look into this though, my graphics card is Nvidia GeForce MX480

**Comment by rodrigorc** [comment]
Glad you made it work.
Unfortunately I don't have access to a Windows PC with two graphics cards...

I'm still interested in getting a screenshot of the failing Papercraft, if you can provide it...

**Comment by Pokefan1067** [comment]
Yeah, That's probably why. I will look into the solution after i get my laptop back, ( It got water damaged D: )

**Comment by rodrigorc** [comment]
Hey @Pokefan1067, have you been able to test the software Opengl?

**Comment by Pokefan1067** [comment]
havent even go my pc back, sadly. i need to get a new mobo for it D:

**Comment by rodrigorc** [comment]
@Pokefan1067: Sorry to hear that. I'm closing the issue with an update to the documentation.

Anyway when I have the time I'll try with a Windows in a Virtual Machine or something similar, that should also lack the proper drivers and behave similarly.
