### ISSUE TITLE
Texture filtering settings.

### ISSUE THREAD

**Issue by DearFox** [rodrigorc/papercraft#3]
Pixel textures are blurry, I would like to be able to adjust this.

**Comment by DearFox** [comment]
![image](https://github.com/rodrigorc/papercraft/assets/59219907/2ce2b2cc-d299-400b-9f97-9c53c9b0eb97)

**Comment by rodrigorc** [comment]
I see, for low-res models, the default texture filtering is not nice.

A workaround would be to upscale the texture image manually doing a "nearest pixel" filter... I've been playing around with this Blockbench tool and I found that you can do that from the program itself: right-click on the texture itself, "resize texture..." and then set a big size such as 1024x1024 and select the "Fill with: Stretch" option.

![image](https://github.com/rodrigorc/papercraft/assets/1128630/76cb8988-616a-48de-b64d-bfca903ac26d)

Anyway having to create a big texture to avoid the filtering seems a bit silly. The proper solution is to add an option somewhere to select the proper texture filter. I think that should be pretty easy...

**Comment by rodrigorc** [comment]
@DearFox 99a9ddfe509b533780fd721ce859d8a21316cb3c now implements this feature.

I've just build [v2.2](https://github.com/rodrigorc/papercraft/releases/tag/v2.2), that includes the option "Texture filter":
![image](https://github.com/rodrigorc/papercraft/assets/1128630/19f68136-3ec5-4684-81ae-1700f01de26e)

Closing this issue as done, but feel free to re-open if you think it can be improved.
