### ISSUE TITLE
[QUESTION] Any plans to add shadow tabs ?

### ISSUE THREAD

**Issue by KntKonataFR** [rodrigorc/papercraft#4]
Just a quick issue post to ask if there is any plan to add Shadow Tabs ? ( [Example](https://i.ibb.co/N1jfXT2/shadow-Tabs.png) )

**Comment by rodrigorc** [comment]
I never heard about Shadow Tabs, but now I'm intrigued.

What is the use for them? Just in the preview window to see how the pieces fit together? Or should they be printed to the final printout? And if so, for what purpose?

**Comment by KntKonataFR** [comment]
Hey ! Thanks for the quick reply !

So basically, you have two ways of doing paper craft:

1/- With a texture, just like the Pikachu you did in the ReadMe;
2/- In "Reverse", so it's printed of coloured paper, and the fold/cut lines end up on the inside of the papercraft, to leave a nice smooth and uniform finish on the outside. [Inside with all the markings](https://i.ibb.co/pXrT8CB/Luffy-Inside.png) - [Smooth outside](https://i.ibb.co/NTJ4rCC/finished-Smooth-Luffy.png)

The shadow tabs are used to align the tabs closest to perfection, because since you are looking inside the model, the actual tab is covering the edge you're trying to glue on, and alignment is hit-or-miss.
( And I also personally use it for my nieces and nephew, but on the outside of the model, because their alignment is also hit-or-miss )

Hope it made some sense !

**Comment by rodrigorc** [comment]
Ok, I get it now, I never though of printing the _inside_ of the model.

So, to answer your original question, yes, I do have plans to implement it. It may take a couple of weeks, it is summer now,

I'll notify you in this issue, if you are willing to test it when it is ready.

**Comment by KntKonataFR** [comment]
No worries, take your time mate !

I've been using Pepakura Designer for as long as I remember, but your software as some really good potential !
I especially like the fact that when stitching faces together, you can see on the 3D view which edge you're hovering, and the fact that you have native SVG export ! ( Pepakura Designer has ESP, EMF and DXF, which is nice to bring your lines straight to your laser cutter, but it a pain in the a** if you want to open the vectors and do some edits / styling to therm )

As I said, don't worry and take your time ! It's summer, it's the best of times to take a break and enjoy life !

**Comment by rodrigorc** [comment]
Hi, @KntKonataFR!

I have just released [v2.3](https://github.com/rodrigorc/papercraft/releases/tag/v2.3) with an option to show the shadow tabs. The shadows themselves were actually quite easy, the tricky part was to limit the tab length so that it does not overflow the adjacent face. Previously that was not a big issue, because if you had a long tab, you'd just cut it shorter before pasting. But with tab shadows you don't have that option!

I think that I managed to create a pretty nifty tab optimization algorithm, if I may say so :nerd_face:.

Can you check if it does what you requested?

**Comment by KntKonataFR** [comment]
Hey !

Sorry for the long delay, haven't been on the computer in a while. I'll make sure to download the updated release and try it out in the next few days, and give you the feedback I can !

**Comment by rodrigorc** [comment]
Hi, @KntKonataFR, it's been a while... have you been able to test this?

**Comment by rodrigorc** [comment]
Closing this issue, already included in v2.3.
