### ISSUE TITLE
Ability to see all connections to an island

### ISSUE THREAD

**Issue by kroozo** [rodrigorc/papercraft#8]
Hi,

Separating from #5 as requested:

>> Working on a complex model was a pretty fluid experience, I really like how once I caught up a start point I could literally get something meaningful done in maybe 10 minutes. I ended up mostly working on the right side, pulling up the pieces one by one to form meaningful islands. I did find myself sweeping around the edges of island quite a lot, to see if there are / where are new pieces, not edges to already existing islands. It may be helpful to be able to briefly show all connections of an island.

> That can be a useful tool, maybe holding "Alt"? But I don't know how easy it would be. Would you mind opening a separate issue for this?

Alt can probably work, yes. I did have some "keep pressed while you want to see" in mind.

**Comment by rodrigorc** [comment]
Hi @kroozo! Can you check the latest commit and comment how you feel about it?

For the highlight I'm keeping the color of the current tool, for consistency. But until now, in "face mode" the edges were never highlighted so it didn't have a color. I've set that to "medium gray", that looks kind of neutral.

Also note that for an unrelated change, *.craft files saved with this version will not be readable by older Papercraft versions.

**Comment by kroozo** [comment]
Hi,

This looks pretty awesome. Not cluttered, consistent, the medium gray works good as well. I think this will be very useful.
